# Generated by Django 5.0.3 on 2025-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provinsi',
            field=models.CharField(choices=[('JT', 'Jawa Tengah'), ('JB', 'Jawa Barat'), ('JT', 'Jawa Timur')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
    ]
