# Generated by Django 5.0.3 on 2025-01-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_provinsi_user_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], max_length=2, null=True),
        ),
    ]
