# Generated by Django 5.0.3 on 2025-01-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message_box',
            new_name='message',
        ),
    ]
